reporttst

diff --git a/.github/workflows/sonarcloud.yml b/.github/workflows/sonarcloud.yml
--- a/.github/workflows/sonarcloud.yml
+++ b/.github/workflows/sonarcloud.yml
@@ -16,6 +16,7 @@ jobs:
         run: mkdir -p reports
 
       - name: Build and Run SonarCloud Scanner
+        id: sonar_scan
         run: |
           docker run --rm -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
           -v ${GITHUB_WORKSPACE}:/usr/src \
@@ -26,12 +27,12 @@ jobs:
           -Dsonar.sources=. \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.issuesReport.html.enable=true \
-          -Dsonar.issuesReport.html.location=./reports/sonar-report.html
+          -Dsonar.issuesReport.html.location=./reports/sonar-report.html || echo "Sonar scan failed"
 
       - name: Check SonarCloud Scanner output
         run: |
-          # Verificar la salida del escáner aquí
-          echo "Checking output..."
+          echo "Sonar scan output:"
+          cat /path/to/your/logs  # Reemplaza esto con la ruta correcta si hay logs
 
       - name: List files in reports directory
         run: ls -la reports/
@@ -48,6 +49,7 @@ jobs:
           | jq -r '.issues[] | "| \(.message) | \(.severity) | \(.component) | \(.line) | \(.status) |"'
 
       - name: Commit and Push HTML Report
+        if: success() && files['reports/sonar-report.html']  # Solo intenta hacer commit si el archivo existe
         run: |
           git config --global user.name "JosueUPT"
           git config --global user.email "actions@github.com"
